apiVersion: v2
name: validators
description: A Helm chart for installing validators with the web3signer.
type: application
version: 1.0.0
appVersion: "v1.0.0"

keywords:
  - ethereum
  - blockchain
  - lighthouse
  - prysm
  - teku
  - validators

