apiVersion: v2
name: dirk
description: A Helm chart for installing and configuring large scale ETH staking infrastructure on top of the Kubernetes
type: application
version: 1.1.0
appVersion: "v22.10.0"

keywords:
  - ethereum
  - blockchain
  - lighthouse
  - prysm
  - teku
  - stakewise

home: https://stakewise.io/

dependencies:
- name: common
  repository: file://../common
  version: 1.0.0
