apiVersion: v2
name: mev-boost
description: mev-boost allows proof-of-stake Ethereum consensus clients to outsource block construction
version: 1.0.0
home: https://boost.flashbots.net/
keywords:
  - ethereum
  - blockchain
  - mev-boost
type: application
appVersion: "1.6.0"

dependencies:
- name: common
  repository: file://../common
  version: 1.0.0
