apiVersion: v2
appVersion: v0.9.9
description: External secret management for Kubernetes
home: https://github.com/external-secrets/external-secrets
icon: https://raw.githubusercontent.com/external-secrets/external-secrets/main/assets/eso-logo-large.png
keywords:
- kubernetes-external-secrets
- secrets
kubeVersion: '>= 1.19.0-0'
maintainers:
  - name: Manjeet-Nethermind
    email: manjeet@nethermind.io
  - name: gehlotanish
    email: anish@nethermind.io
name: external-secrets
type: application
version: 0.9.10
