apiVersion: v2
name: posmoni
description: A Helm chart for installing and configuring Posmoni
type: application
version: 1.0.0
appVersion: "v0.0.1"

keywords:
  - ethereum

home: https://nethermind.io/

dependencies:
- name: common
  repository: file://../common
  version: 1.0.0
