{{- if .Values.externalSecretsV2.enabled }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: eso-{{ include "common.names.fullname" . }}
  labels:
    {{- include "common.labels.standard" . | nindent 4 }}
spec:
  refreshInterval: 10m
  secretStoreRef:
    name: {{ .Values.externalSecretsV2.secretStoreRef.name }}
    kind: {{ .Values.externalSecretsV2.secretStoreRef.kind }}
  target:
    name: eso-{{ include "common.names.fullname" . }}
    creationPolicy: Owner
  data:
    {{- .Values.externalSecretsV2.data | toYaml | trim | nindent 2 }}
{{- end }}
