{{- if .Values.externalSecrets.enabled }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: eso-{{ include "common.names.fullname" . }}
  labels:
    {{- include "common.labels.standard" . | nindent 4 }}
spec:
  refreshInterval: 10m
  secretStoreRef:
    name: {{ .Values.externalSecrets.secretStoreRef.name }}
    kind: {{ .Values.externalSecrets.secretStoreRef.kind }}
  target:
    name: eso-{{ include "common.names.fullname" . }}
    creationPolicy: Owner
  data:
    - secretKey: ESO_DECRYPTION_KEY
      remoteRef:
        key: validators
        property: decryptionKey
    - secretKey: ESO_DB_KEYSTORE_URL
      remoteRef:
        key: validators
        property: dbKeystoreUrl
    - secretKey: ESO_DB_URL
      remoteRef:
        key: validators
        property: dbUrl
    - secretKey: ESO_DB_USERNAME
      remoteRef:
        key: validators
        property: dbUsername
    - secretKey: ESO_DB_PASSWORD
      remoteRef:
        key: validators
        property: dbPassword
    {{- .Values.externalSecrets.data | toYaml | trim | nindent 2 }}
{{- end }}
