{{- if $.Values.svc.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Values.deployment.projectName }}-alb
  namespace: {{ .Values.deployment.namespace }}
  annotations:
    kubernetes.io/ingress.class: "gce"
    cert-manager.io/acme-challenge-type: http01
    cert-manager.io/cluster-issuer: letsencrypt-gce
    ingress.kubernetes.io/force-ssl-redirect: "true"
    kubernetes.io/tls-acme: "true"
spec:
  rules:
{{ toYaml .Values.svc.ingress.rules | indent 2 }}
  tls:
  - hosts:
    - {{ .Values.svc.ingress.host }}
    secretName: {{ .Values.deployment.projectName }}-alb-tls-cert
{{- if $.Values.svc.ingress.extraHost.enabled }}
  - hosts:
    - "{{ .Values.svc.ingress.extraHost.host1 }}"
    secretName: {{ .Values.deployment.projectName }}-host1-alb-tls-cert
  - hosts:
    - "{{ .Values.svc.ingress.extraHost.host2 }}"
    secretName: {{ .Values.deployment.projectName }}-host2-alb-tls-cert
  - hosts:
    - "{{ .Values.svc.ingress.extraHost.host3 }}"
    secretName: {{ .Values.deployment.projectName }}-host3-alb-tls-cert
{{- end -}}
{{- end -}}
