{{- if .Values.enabled }}
{{- $root := . -}}
{{- $counter := 0 }}
{{- range (untilStep (int .Values.validatorsKeyIndex) (int (add .Values.validatorsKeyIndex .Values.validatorsCount)) 1) }}

{{ $rpcEndpoints := list }}
{{- if $.Values.beaconChainRpcEndpointsRandomized }}
{{- $rpcList := list }}
{{- range (untilStep $counter (len $.Values.beaconChainRpcEndpointsRandomized) 1) }}
{{ $rpcList = append $rpcList (index $.Values.beaconChainRpcEndpointsRandomized .) }}
{{- end }}
{{ $rpcList = append $rpcList $.Values.beaconChainRpcEndpointsRandomized }}
{{ $rpcEndpoints = include "flatten" $rpcList }}
{{- if ge $counter (len $.Values.beaconChainRpcEndpointsRandomized) }}
  {{- $counter = 1 }}
{{- else }}
  {{ $counter = int (add1 $counter) }}
{{- end }}
{{- end }}

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ template "validators.fullname" $root }}-validator{{.}}
  labels:
    {{- include "validator.labels" $root | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "validators.selectorLabels" $root | nindent 6 }}
  serviceName: {{ template "validators.fullname" $root }}
  template:
    metadata:
      labels:
        {{- include "validators.selectorLabels" $root | nindent 8 }}
      annotations:
        checksum/configmap: {{ include (print $root.Template.BasePath "/configmap.yaml") $root | sha256sum }}
    spec:
      {{- with (concat $root.Values.imagePullSecrets $root.Values.global.imagePullSecrets) }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with $root.Values.terminationGracePeriodSeconds }}
      terminationGracePeriodSeconds: {{ . }}
      {{- end }}
      {{- with $root.Values.affinity }}
      affinity:
        {{ toYaml . | nindent 8 | trim }}
      {{- end }}
      {{- with $root.Values.tolerations }}
      tolerations:
        {{ toYaml . | nindent 8 | trim }}
      {{- end }}
      {{- with $root.Values.nodeSelector }}
      nodeSelector:
        {{ toYaml . | nindent 8 | trim }}
      {{- end }}
      {{- with $root.Values.securityContext }}
      securityContext:
        {{ toYaml . | nindent 8 | trim }}
      {{- end }}
      serviceAccountName: "validators"
      priorityClassName: {{ $root.Values.priorityClassName | quote }}
      initContainers:
        - name: get-configs
          image: "{{ $root.Values.cliImage.repository }}:{{ $root.Values.cliImage.tag }}"
          imagePullPolicy: {{ $root.Values.cliImage.pullPolicy }}
          securityContext:
            runAsUser: 0
          env:
            - name: WEB3SIGNER_URL
              value: {{ $root.Values.web3signerEndpoint }}
          args:
            - "sync-validator-keys"
            - "--db-url"
            - "{{ $root.Values.dbKeystoreUrl }}"
            - "--output-dir"
            - "/data"
            - "--index"
            - "{{ . }}"
            {{- if eq $root.Values.network "sepolia" }}
            - "--network"
            - "goerli"
            {{- else }}
            - "--network"
            - "{{ $root.Values.network }}"
            {{- end }}
          {{- if $root.Values.feeOverride }}
            - "--solo-fees-file"
            - "/fee/feeOverride.json"
          {{- end }}
          {{- if not $root.Values.enableBuilder }}
            - "--proposal-builder-enabled"
            - "false"
          {{- end }}
          volumeMounts:
            - name: data
              mountPath: /data
          {{- if $root.Values.feeOverride }}
            - name: fee-override
              mountPath: /fee
          {{- end }}
        - name: prepare
          image: "{{ $root.Values.initImageBusybox.repository }}:{{ $root.Values.initImageBusybox.tag }}"
          imagePullPolicy: {{ $root.Values.initImageBusybox.pullPolicy }}
          securityContext:
            runAsUser: 0
          command:
            - sh
            - -c
            - >
              ls -lha /data;
              mkdir -p /data/lighthouse/validators;
              cp /data/validator_definitions.yml /data/lighthouse/validators/validator_definitions.yml;
              cp /mnt/gnosis-prysm/config.yaml /data/config_gnosis_prysm;
              cat /data/signer_keys.yml > /data/config;
              cat /data/config;
              cat /data/proposerConfig.json;
              echo "" >>
              cat /data/signer_keys.yml >> /data/config_gnosis_prysm;
              cat /data/config_gnosis_prysm;
              chown -R {{ $root.Values.securityContext.runAsUser }}:{{ $root.Values.securityContext.runAsUser }} /data;
              echo "Replace gnosis fee recipient";
              grep -rl -i "0x6A9d30e05C6832E868390F155388c7d97A6faEAC" -r /data/ | xargs --no-run-if-empty sed -i "s/0x6A9d30e05C6832E868390F155388c7d97A6faEAC/{{ $.Values.suggestedFeeRecipient }}/g";
              echo "Replace mainnet fee recipient";
              grep -rl -i "0x6b333B20fBae3c5c0969dd02176e30802e2fbBdB" -r /data/ | xargs --no-run-if-empty sed -i "s/0x6b333B20fBae3c5c0969dd02176e30802e2fbBdB/{{ $.Values.suggestedFeeRecipient }}/g";
              echo "Replace gnosis fee recipient";
              grep -rl -i "0x0000000000000000000000000000000000000000" -r /data/ | xargs --no-run-if-empty sed -i "s/0x0000000000000000000000000000000000000000/{{ $.Values.suggestedFeeRecipient }}/g";
          volumeMounts:
            - name: data
              mountPath: /data
            - name: gnosis-prysm
              mountPath: /mnt/gnosis-prysm
      containers:
        - name: validator
          image: "{{ (pluck $root.Values.type $root.Values.image | first ).repository }}:{{ (pluck $root.Values.type $root.Values.image | first ).tag }}"
          imagePullPolicy: {{ $root.Values.image.pullPolicy }}
          args:
            {{- range (pluck $root.Values.type $root.Values.flags | first) }}
            - {{ . | quote }}
            {{- end -}}

            {{- if and (eq $root.Values.type "prysm") (ne $root.Values.network "gnosis") }}
            - "--{{ $root.Values.network }}"
            - "--config-file=/data/config"
            - "--validators-external-signer-url={{ $.Values.web3signerEndpoint }}"
            - "--proposer-settings-file=/data/proposerConfig.json"
            {{- else if and (eq $root.Values.type "prysm") (eq $root.Values.network "gnosis") }}
            - "--config-file /data/config_gnosis_prysm"
            - "--chain-config-file /data/config_gnosis_prysm"
            - "--validators-external-signer-url={{ $.Values.web3signerEndpoint }}"
            {{- else if eq $root.Values.type "lighthouse" }}
            - "--network={{ $root.Values.network }}"
            {{- else if eq $root.Values.type "teku" }}
            - "--network=auto"
            - "--config-file=/data/config"
            - "--validators-external-signer-url={{ $.Values.web3signerEndpoint }}"
            - "--validators-proposer-config=/data/proposerConfig.json"
            {{- if $root.Values.enableBuilder }}
            - "--validators-proposer-blinded-blocks-enabled=true"
            {{- end }}
            {{- end }}

            {{- include "validator-graffiti" $ | nindent 12 }}

          {{- if $.Values.beaconChainRpcEndpointsRandomized }}
            {{- if eq $.Values.type "prysm" }}
            - "--beacon-rpc-provider={{ $rpcEndpoints }}"
            {{- else if eq $.Values.type "lighthouse" }}
            - "--beacon-nodes={{ $rpcEndpoints }}"
            {{- else if eq $.Values.type "teku" }}
            {{- $beaconChainRpcEndpointsLen := len $.Values.beaconChainRpcEndpointsRandomized }}
            {{- if gt $beaconChainRpcEndpointsLen 1 }}
            - "--beacon-node-api-endpoints={{ $rpcEndpoints | join "," }}"
            {{- else }}
            - "--beacon-node-api-endpoint={{ $rpcEndpoints }}"
            {{- end }}
            {{- end }}
          {{- else }}
            {{- include "beacon-rpc-node" $ | nindent 12 }}
          {{- end }}

            {{- if $root.Values.metrics.enabled }}
            {{- range (pluck $root.Values.type $root.Values.metrics.flags | first) }}
            - {{ . | quote }}
            {{- end }}
            {{- end }}

            {{- range (pluck $root.Values.type $root.Values.extraFlags | first) }}
            - {{ . | quote }}
            {{- end -}}

          {{- if $root.Values.metrics.enabled }}
          ports:
            - containerPort: {{ $root.Values.metrics.port }}
              name: metrics
              protocol: TCP
          {{- end }}
          {{- with (pluck $root.Values.type $root.Values.readinessProbe | first) }}
          readinessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with (pluck $root.Values.type $root.Values.livenessProbe | first) }}
          livenessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with $root.Values.resources }}
          resources:
            {{ toYaml . | nindent 12 }}
          {{- end }}
          volumeMounts:
            - name: data
              mountPath: /data
      volumes:
        - name: gnosis-prysm
          configMap:
            name: {{ template "validators.fullname" $root }}-gnosis-prysm
      {{- if $root.Values.feeOverride }}
        - name: fee-override
          configMap:
            name: {{ template "validators.fullname" $root }}-override-fee-recipient
      {{- end }}
        - name: data
          emptyDir: {}

{{- end }}
{{- end }}
