---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "vouch.fullname" . }}
  labels:
    {{- include "vouch.labels" . | nindent 4 }}
  annotations:
    prometheus.io/probe: "true"
spec:
  type: {{ .Values.service.type }}
  clusterIP: None
  ports:
    - port: {{ .Values.service.httpPort }}
      targetPort: http
      protocol: TCP
      name: http
    - port: {{ .Values.blockRelayPort }}
      targetPort: blockrelay
      protocol: TCP
      name: blockrelay
    - port: {{ .Values.metricsPort }}
      targetPort: metrics
      protocol: TCP
      name: metrics
  selector:
    {{- include "vouch.selectorLabels" . | nindent 4 }}