{{- if or .Values.geth.http.enabled .Values.geth.ws.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "common.names.fullname" . }}-geth
  labels:
    {{- include "common.labels.standard" . | nindent 4 }}
spec:
{{- if .Values.geth.svcHeadless }}
  clusterIP: None
{{- end }}
{{- if .Values.geth.sessionAffinity.enabled }}
  sessionAffinity: ClientIP
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: {{ .Values.sessionAffinity.timeoutSeconds }}
{{- end }}
  type: ClusterIP
  ports:
  {{- if .Values.global.JWTSecret }}
    - name: authrpc
      port: {{ .Values.geth.authRpc.port }}
      targetPort: authrpc
  {{- end }}
  {{- if .Values.geth.http.enabled }}
    - name: http
      port: {{ .Values.geth.http.port }}
      targetPort: http
  {{- end }}
  {{- if .Values.geth.ws.enabled }}
    - name: ws
      port: {{ .Values.geth.ws.port }}
      targetPort: ws
  {{- end }}
  {{- if .Values.global.metrics.enabled }}
    - name: metrics
      port: {{ .Values.geth.metrics.port }}
      targetPort: metrics
  {{- end }}
  selector:
    {{- include "common.labels.matchLabels" . | nindent 4 }}
{{- end }}
