---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "common.names.fullname" . }}
  labels:
    {{- include "common.labels.standard" . | nindent 4 }}
{{- if and .Values.global.metrics.enabled .Values.metrics.svcAnnotations }}
  annotations:
    {{ toYaml .Values.metrics.svcAnnotations | nindent 4 | trim }}
{{- end }}
spec:
  selector:
    {{- include "common.labels.matchLabels" . | nindent 4 }}
{{- if .Values.sessionAffinity.enabled }}
  sessionAffinity: ClientIP
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: {{ .Values.sessionAffinity.timeoutSeconds }}
{{- end }}
  type: ClusterIP
{{- if .Values.svcHeadless }}
  clusterIP: None
{{- end }}
  ports:
    - name: {{ .Values.http.portName }}
      port: {{ .Values.http.port }}
      targetPort: {{ .Values.http.portName }}
  {{- if .Values.global.metrics.enabled }}
    - name: metrics
      port: {{ .Values.metrics.port }}
      targetPort: metrics
  {{- end }}
