apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "common.names.fullname" . }}
  labels:
    {{- include "common.labels.standard" . | nindent 4 }}
data:
  LOG_LEVEL: {{ .Values.settings.logLevel | quote }}
  NETWORK: {{ .Values.settings.network | quote }}
  IPFS_LOCAL_CLIENT_ENDPOINT: {{ .Values.settings.ipfsLocalClientEndpoint | quote }}
  EXECUTION_ENDPOINT: {{ .Values.settings.executionEndpoint | quote }}
  CONSENSUS_ENDPOINT: {{ .Values.settings.consensusEndpoint | quote }}
  POSTGRES_DB: {{ .Values.settings.postgresDb | quote }}
  POSTGRES_PORT: {{ .Values.settings.postgresPort | quote }}
  POSTGRES_USER: {{ .Values.settings.postgresUser | quote }}
  POSTGRES_HOST: {{ .Values.settings.postgresHostname | quote }}
  RSA_PRIVATE_KEY_PATH: "/secret/rsakey"
