apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "common.names.fullname" . }}
  labels:
    {{- include "common.labels.standard" . | nindent 4 }}
data:
  LOG_LEVEL: {{ .Values.settings.logLevel | quote }}
  NETWORK: {{ .Values.settings.network | quote }}
  IPFS_LOCAL_CLIENT_ENDPOINT: {{ .Values.settings.ipfsLocalClientEndpoint | quote }}
  EXECUTION_ENDPOINTS: {{ .Values.settings.executionEndpoints | quote }}
  CONSENSUS_ENDPOINTS: {{ .Values.settings.consensusEndpoints | quote }}
  IPFS_FETCH_ENDPOINTS: {{ .Values.settings.ipfsFetchEndpoints | quote }}
  DATABASE: "/data/oracle.db"
  VALIDATORS_WITHDRAWALS_CONCURRENCY: {{ .Values.settings.validatorsWithdrawalsConcurrency | quote }}
  DEFAULT_RETRY_TIME: {{ .Values.settings.defaultRetryTime | quote }}
  CONSENSUS_BLOCK_CHUNK_SIZE: {{ .Values.settings.consensusBlockChunkSize | quote }}
  EVENTS_BLOCKS_RANGE_INTERVAL: {{ .Values.settings.eventsBlockRangeInterval | quote }}
