# Default values for oracle.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# Pod Security Context
# ref: https://kubernetes.io/docs/tasks/configure-pod-container/security-context/
securityContext:
  fsGroup: 1001
  runAsUser: 1001

# Termination Grace Period
# https://kubernetes.io/docs/tasks/run-application/force-delete-stateful-set-pod/#delete-pods
terminationGracePeriodSeconds: 1800

# Affinity Settings
# https://kubernetes.io/docs/concepts/configuration/assign-pod-node/#affinity-and-anti-affinity
affinity: { }

# Toleration Settings
# https://kubernetes.io/docs/concepts/scheduling-eviction/taint-and-toleration/
tolerations: [ ]

# Docker image
image:
  repository: "stakewiselabs/oracle"
  tag: "HEAD-320875c"
  pullPolicy: IfNotPresent

# Configure resource requests and limits.
# http://kubernetes.io/docs/user-guide/compute-resources/
resources:
  requests:
    cpu: 10m
    memory: 200Mi

# used to assign priority to pod
# ref: https://kubernetes.io/docs/concepts/configuration/pod-priority-preemption/
priorityClassName: ""

settings:
  # notifications
  sendTelegramNotifications: "True"
  telegramToken: ""
  telegramChatId: ""

  # connections
  web3WsEndpoint: "ws://<eth1 chain endpoint>"
  web3WsEndpointTimeout: "60"
  web3HttpEndpoint: ""
  beaconChainRpcEndpoint: "<eth2 chain endpoint>"

  etherscanAddressBaseUrl: "https://etherscan.io/address/"

  # middlewares
  injectPOAMiddleware: "False"
  injectStaleCheckMiddleware: "False"
  staleCheckMiddlewareAllowableDelay: "120"
  injectRetryRequestMiddleware: "False"
  injectLocalFilterMiddleware: "False"
  applyGasPriceStrategy: "False"
  maxTxWaitSeconds: "180"
  oracleVoteGasLimit: "250000"

  # oracle balance
  balanceWarningThreshold: "0.05"
  balanceErrorThreshold: "0.008"

  # transactions
  transactionTimeout: "1800"

  # processing interval
  processInterval: "300"

  # contracts
  poolContractAddress: "0x0"
  rewardEthContractAddress: "0x0"
  stakedEthContractAddress: "0x0"
  oraclesContractAddress: "0x0"
  daoAddress: "0x0"
  multicallContractAddress: "0x0"
  merkleDistributorContractAddress: "0x0"
  balancerVaultContractAddress: "0x0"
  uniswapV3PositionManagerContractAddress: "0x0"
  ensResolverContractAddress: "0x0"

  daoEnsDomain: "stakewise.eth"
  oracleEnsTextRecord: "oraclesconfig"
  balancerSubgraphUrl: "https://api.thegraph.com/subgraphs/name/balancer-labs/balancer-v2"
  uniswapV2subgraphUrl: "https://api.thegraph.com/subgraphs/name/uniswap/uniswap-v2"
  # TODO: replace with official Uniswap v3 graph
  uniswapV3subgraphUrl: "https://api.thegraph.com/subgraphs/name/ianlapham/uniswap-v3-subgraph"
  ipfsEndpoint: "/dns/ipfs.infura.io/tcp/5001/https"


  # credentials
  oraclePrivateKey: ""
