apiVersion: v2
name: operator
description: A Helm chart for installing and configuring large scale ETH staking infrastructure on top of the Kubernetes

# A chart can be either an 'application' or a 'library' chart.
#
# Application charts are a collection of templates that can be packaged into versioned archives
# to be deployed.
#
# Library charts provide useful utilities or functions for the chart developer. They're included as
# a dependency of application charts to inject those utilities and functions into the rendering
# pipeline. Library charts do not define any templates and therefore cannot be deployed.
type: application

# This is the chart version. This version number should be incremented each time you make changes
# to the chart and its templates, including the app version.
# Versions are expected to follow Semantic Versioning (https://semver.org/)
version: 2.1.1

# This is the version number of the application being deployed. This version number should be
# incremented each time you make changes to the application. Versions are not expected to
# follow Semantic Versioning. They should reflect the version the application is using.
# It is recommended to use it with quotes.
appVersion: "v2.0.6"

keywords:
  - ethereum
  - blockchain
  - lighthouse
  - prysm
  - geth
  - erigon
  - stakewise
  - p2p

home: https://stakewise.io/

dependencies:
  - name: vault
    repository: https://helm.releases.hashicorp.com
    version: 0.18.0
    condition: vault.enabled
  - name: geth
    repository: https://charts.stakewise.io
    version: "1.0.2"
    condition: geth.enabled
  - name: erigon
    repository: https://charts.stakewise.io
    version: "1.0.3"
    condition: erigon.enabled
  - name: prysm
    repository: https://charts.stakewise.io
    version: "1.0.5"
    condition: prysm.enabled
  - name: lighthouse
    repository: https://charts.stakewise.io
    version: "0.1.0"
    condition: lighthouse.enabled
  - name: teku
    repository: https://charts.stakewise.io
    version: "0.1.0"
    condition: teku.enabled

