apiVersion: v2
name: prysm
version: 2.1.0
appVersion: v2.1.4
kubeVersion: "^1.18.0-0"
description: Go implementation of Ethereum proof of stake.
type: application
keywords:
  - ethereum
  - blockchain
  - prysm
  - p2p
home: https://www.ethereum.org/
sources:
  - https://github.com/prysmaticlabs/prysm
maintainers:
  - name: Dmitri Tsumak
    email: dmitri@stakewise.io
icon: https://raw.githubusercontent.com/ethereum/ethereum-org/master/public/images/logos/ETHEREUM-ICON_Black.png

dependencies:
- name: common
  repository: file://../common
  version: 1.0.0
