{{- if or .Values.restApi.enabled .Values.metrics.enabled }}
{{- $root := . -}}
{{- range $i, $e := until (len $root.Values.global.executionEndpoints) }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "common.names.fullname" $root }}-{{ $i }}
  labels:
    {{- include "common.labels.standard" $root | nindent 4 }}
    replicaID: {{ $i | quote }}
spec:
  type: {{ $root.Values.service.type }}
{{- if $root.Values.svcHeadless }}
  clusterIP: None
{{- end }}
{{- if $root.Values.sessionAffinity.enabled }}
  sessionAffinity: ClientIP
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: {{ $root.Values.sessionAffinity.timeoutSeconds }}
{{- end }}
  ports:
  {{- if $root.Values.restApi.enabled }}
    - port: {{ $root.Values.restApi.port }}
      targetPort: {{ $root.Values.restApi.portName }}
      protocol: TCP
      name: {{ $root.Values.restApi.portName }}
  {{- end }}
  {{- if $root.Values.metrics.enabled }}
    - port: {{ $root.Values.metrics.port }}
      targetPort: metrics
      protocol: TCP
      name: metrics
  {{- end }}
  selector:
    {{- include "common.labels.matchLabels" $root | nindent 4 }}
    replicaID: {{ $i | quote }}
{{- end }}

{{- end }}
