---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "common.names.fullname" . }}-init
  labels:
    {{- include "common.labels.standard" . | nindent 4 }}
data:
  init.sh: |
    #!/bin/sh
{{- if or (and .Values.execution.persistence.enabled .Values.execution.initChownData) (and .Values.beacon.persistence.enabled .Values.beacon.initChownData) (.Values.sharedPersistence.enabled) }}
    # mkdir -p /data && chown -R {{ .Values.global.podSecurityContext.runAsUser }}:{{ .Values.global.podSecurityContext.runAsUser }} /data;
    mkdir -p /data/beacon && chown -R {{ .Values.global.podSecurityContext.runAsUser }}:{{ .Values.global.podSecurityContext.runAsUser }} /data/beacon;
{{- end }}
    echo "Namespace: ${POD_NAMESPACE} Pod: ${POD_NAME}";
{{- if .Values.global.p2pNodePort.enabled }}
  {{- if eq .Values.global.p2pNodePort.type "LoadBalancer" }}
      export POD_NUMBER_SUFFIX=$(echo "${POD_NAME}" | grep -o -E '[0-9]+$')
      export POD_PREFIX_NAME={{ include "common.names.fullname" . }}
      for SERVICE_TYPE in beacon execution; do 
        SERVICE_NAME="${POD_PREFIX_NAME}-${SERVICE_TYPE}-${POD_NUMBER_SUFFIX}"
        until [ -n "$(kubectl -n ${POD_NAMESPACE} get svc/${SERVICE_NAME} -o jsonpath='{.status.loadBalancer.ingress[0].ip}')" ]; do
          echo "Waiting for load balancer to get an IP for ${SERVICE_NAME}" && sleep 10
        done
      done
      export EXTERNAL_EXECUTION_PORT=$(kubectl -n ${POD_NAMESPACE} get services -l "client=execution,pod in (${POD_NAME}), type in (p2p)" -o jsonpath='{.items[0].spec.ports[0].nodePort}')
      export EXTERNAL_BEACON_PORT=$(kubectl -n ${POD_NAMESPACE} get services -l "client=beacon,pod in (${POD_NAME}), type in (p2p)" -o jsonpath='{.items[0].spec.ports[0].nodePort}')
      export EXTERNAL_IP=$(kubectl -n ${POD_NAMESPACE} get svc/${POD_PREFIX_NAME}-beacon-${POD_NUMBER_SUFFIX} -o jsonpath='{.status.loadBalancer.ingress[0].ip}')
  {{- else }}
      export EXTERNAL_EXECUTION_PORT=$(kubectl get services -l "client=execution,pod in (${POD_NAME}), type in (p2p)" -o jsonpath='{.items[0].spec.ports[0].nodePort}')
      export EXTERNAL_BEACON_PORT=$(kubectl get services -l "client=beacon,pod in (${POD_NAME}), type in (p2p)" -o jsonpath='{.items[0].spec.ports[0].nodePort}')
      export EXTERNAL_IP=$(kubectl get nodes "${NODE_NAME}" -o jsonpath='{.status.addresses[?(@.type=="ExternalIP")].address}')
  {{- end }}
      echo "EXTERNAL_EXECUTION_PORT=$EXTERNAL_EXECUTION_PORT" >  /env/init-nodeport
      echo "EXTERNAL_BEACON_PORT=$EXTERNAL_BEACON_PORT" >> /env/init-nodeport
      echo "EXTERNAL_IP=$EXTERNAL_IP"     >> /env/init-nodeport
      cat /env/init-nodeport
  {{- if eq .Values.beacon.client "prysm" }}
      touch /data/beacon/config.yaml
      echo "p2p-host-ip: $EXTERNAL_IP" > /data/beacon/config.yaml
      echo "p2p-tcp-port: $EXTERNAL_BEACON_PORT" >> /data/beacon/config.yaml
      echo "p2p-udp-port: $EXTERNAL_BEACON_PORT" >> /data/beacon/config.yaml
      echo "Updated Prysm config.yaml file at /data/beacon/config.yaml"
  {{- end }}
      if [ -f "/data/beacon/config.yaml" ]; then echo "Beacon client config:" && cat "/data/beacon/config.yaml"; fi
{{- end }}
