---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "common.names.fullname" . }}
  labels:
    {{- include "common.labels.standard" . | nindent 4 }}
    pod: "{{ include "common.names.fullname" . }}"
    type: api
    execution: {{ .Values.execution.client }}
    beacon: {{ .Values.beacon.client }}
{{- if and .Values.execution.metrics.enabled .Values.execution.metrics.svcAnnotations }}
  annotations:
    {{ toYaml .Values.execution.metrics.svcAnnotations | nindent 4 | trim }}
{{- else }}
  annotations:
      {{ toYaml .Values.beacon.metrics.svcAnnotations | nindent 4 | trim }}
{{- end }}
spec:
{{- if .Values.global.sessionAffinity.enabled }}
  sessionAffinity: ClientIP
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: {{ .Values.global.sessionAffinity.timeoutSeconds }}
{{- end }}
  type: {{ .Values.global.service.type }} # ClusterIP, NodePort, LoadBalancer, or ExternalName
{{- if .Values.global.service.svcHeadless}}
  clusterIP: None
{{- end }}
  ports:
  {{- if .Values.execution.jsonrpc.enabled }}
    - name: jsonrpc-exec
      port: {{ .Values.execution.jsonrpc.http.port }}
      targetPort: jsonrpc-exec
    - port: {{ .Values.execution.jsonrpc.engine.port }}
      targetPort: engine-exec
      name: engine-exec
  {{- end }}
  {{- if eq .Values.execution.client "erigon" }}
    - name: grpc-exec
      protocol: TCP
      port: {{ .Values.execution.jsonrpc.grpc.port }}
      targetPort: grpc-exec
  {{- end }}
  {{- if .Values.execution.jsonrpc.websocket.enabled }}
    - name: ws-exec
      port: {{ .Values.execution.jsonrpc.websocket.port }}
      targetPort: ws-exec
      protocol: TCP
  {{- end }}
  {{- if .Values.execution.metrics.enabled }}
    - name: metrics-exec
      port: {{ .Values.execution.metrics.port }}
      targetPort: metrics-exec
      protocol: TCP
  {{- end }}
  {{- if and (eq .Values.beacon.client "prysm") .Values.beacon.grpc.enabled }}
    - name: {{ .Values.beacon.grpc.portName }}-beacon
      port: {{ .Values.beacon.grpc.port }}
      targetPort: {{ .Values.beacon.grpc.portName }}-beacon
  {{- end }}
  {{- if .Values.beacon.restApi.enabled }}
    - name: http-beacon
      port: {{ index .Values.beacon.restApi.portMap .Values.beacon.client }}
      targetPort: http-beacon
  {{- end }}
  {{- if and .Values.global.metrics.enabled .Values.beacon.metrics.enabled }}
    - name: metrics-beacon
      port: {{ .Values.beacon.metrics.port }}
      targetPort: metrics-beacon
  {{- end }}
  selector:
    {{- include "common.labels.matchLabels" . | nindent 4 }}
