# Chart.yaml
apiVersion: v2
name: my-mysql-chart
description: A Helm chart for deploying MySQL with StatefulSet, Service, Secret, and PVC.
version: 1.0.1
appVersion: "5.7"
maintainers:
  - name: Manjeet-Nethermind
    email: manjeet@nethermind.io
  - name: gehlotanish
    email: anish@nethermind.io
