# Default values for ipfs.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

global:
  serviceAccount:
    create: true

## How many ipfs instances to run simultaneously
##
replicaCount: 1

## Pod Security Context
## ref: https://kubernetes.io/docs/tasks/configure-pod-container/security-context/
##
securityContext:
  fsGroup: 1001
  runAsUser: 1001

## Init image is used to chown data volume, initialise genesis, etc.
##
initImage:
  registry: "docker.io"
  repository: "busybox"
  tag: "1.34"
  pullPolicy: IfNotPresent

image:
  registry: "docker.io"
  repository: ipfs/kubo
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: "v0.18.1"

podMonitor:
  enabled: true
  labels:
    release: prometheus-community

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

## IPFS Configuration
##
ipfs:
  # Data Path
  path: /data/ipfs
  # The profile of your IPFS node allows you to specify which
  # file-system or data-store you want to use.
  # Changing these options will affect the performance of your node.
  # For example, if you want to have a faster datastore for your node,
  # you can use the badgerds profile. If you're running your node on
  # a low-power device like a Raspberry Pi, you can use the lowpower profile.
  # Profiles have been developed to customize your IPFS node to perform
  # best under given conditions.
  profile: server
  # Sets the file descriptor limit for go-ipfs.
  # If go-ipfs fails to set the file descriptor limit, it will log an error.
  fdMax: "8192"
  # go-ipfs tries to reuse the same source port for all connections
  # to improve NAT traversal.
  tcpReusePort: "true"
  # Sets the log level for go-ipfs. It can be set to one of:
  # CRITICAL, ERROR, WARNING, NOTICE, INFO, DEBUG
  logging: error
  # Sets the log message format. Can be one of:
  # color, nocolor
  loggingFmt: color
  # Enables fuse debug logging.
  fuseDebug: "false"
  # Enables debug logging for the yamux stream muxer.
  yamuxDebug: "false"
  datastoreStorageMax: "100Gi"
  peers: |
    '[{"Addr":["/dnsaddr/node-1.ingress.cloudflare-ipfs.com"],"ID":"QmcFf2FH3CEgTNHeMRGhN7HNHU1EXAxoEk6EFuSyXCsvRE"},{"Addr":["/dnsaddr/node-2.ingress.cloudflare-ipfs.com"],"ID":"QmcFmLd5ySfk2WZuJ1mfSWLDjdmHZq7rSAua4GoeSQfs1z"},{"Addr":["/dnsaddr/node-3.ingress.cloudflare-ipfs.com"],"ID":"QmcfFmzSDVbwexQ9Au2pt5YEXHK5xajwgaU6PpkbLWerMa"},{"Addr":["/dnsaddr/node-4.ingress.cloudflare-ipfs.com"],"ID":"QmcfJeB3Js1FG7T8YaZATEiaHqNKVdQfybYYkbT1knUswx"},{"Addr":["/dnsaddr/node-5.ingress.cloudflare-ipfs.com"],"ID":"QmcfVvzK4tMdFmpJjEKDUoqRgP4W9FnmJoziYX5GXJJ8eZ"},{"Addr":["/dnsaddr/node-6.ingress.cloudflare-ipfs.com"],"ID":"QmcfZD3VKrUxyP9BbyUnZDpbqDnT7cQ4WjPP8TRLXaoE7G"},{"Addr":["/dnsaddr/node-7.ingress.cloudflare-ipfs.com"],"ID":"QmcfZP2LuW4jxviTeG8fi28qjnZScACb8PEgHAc17ZEri3"},{"Addr":["/dnsaddr/node-8.ingress.cloudflare-ipfs.com"],"ID":"QmcfgsJsMtx6qJb74akCw1M24X1zFwgGo11h1cuhwQjtJP"},{"Addr":["/dnsaddr/node-9.ingress.cloudflare-ipfs.com"],"ID":"Qmcfr2FC7pFzJbTSDfYaSy1J8Uuy8ccGLeLyqJCKJvTHMi"},{"Addr":["/dnsaddr/node-10.ingress.cloudflare-ipfs.com"],"ID":"QmcfR3V5YAtHBzxVACWCzXTt26SyEkxdwhGJ6875A8BuWx"},{"Addr":["/dnsaddr/node-11.ingress.cloudflare-ipfs.com"],"ID":"Qmcfuo1TM9uUiJp6dTbm915Rf1aTqm3a3dnmCdDQLHgvL5"},{"Addr":["/dnsaddr/node-12.ingress.cloudflare-ipfs.com"],"ID":"QmcfV2sg9zaq7UUHVCGuSvT2M2rnLBAPsiE79vVyK3Cuev"},{"Addr":["/dnsaddr/fra1-1.hostnodes.pinata.cloud"],"ID":"QmWaik1eJcGHq1ybTWe7sezRfqKNcDRNkeBaLnGwQJz1Cj"},{"Addr":["/dnsaddr/fra1-2.hostnodes.pinata.cloud"],"ID":"QmNfpLrQQZr5Ns9FAJKpyzgnDL2GgC6xBug1yUZozKFgu4"},{"Addr":["/dnsaddr/fra1-3.hostnodes.pinata.cloud"],"ID":"QmPo1ygpngghu5it8u4Mr3ym6SEU2Wp2wA66Z91Y1S1g29"},{"Addr":["/dnsaddr/nyc1-1.hostnodes.pinata.cloud"],"ID":"QmRjLSisUCHVpFa5ELVvX3qVPfdxajxWJEHs9kN3EcxAW6"},{"Addr":["/dnsaddr/nyc1-2.hostnodes.pinata.cloud"],"ID":"QmPySsdmbczdZYBpbi2oq2WMJ8ErbfxtkG8Mo192UHkfGP"},{"Addr":["/dnsaddr/nyc1-3.hostnodes.pinata.cloud"],"ID":"QmSarArpxemsPESa6FNkmuu9iSE1QWqPX2R3Aw6f5jq4D5"}]'
  bootstrap: '[]'
  addressesNoAnnounce: |
    '["/ip4/100.64.0.0/ipcidr/10","/ip4/169.254.0.0/ipcidr/16","/ip4/192.0.0.0/ipcidr/24","/ip4/192.0.2.0/ipcidr/24","/ip4/192.168.0.0/ipcidr/16","/ip4/198.18.0.0/ipcidr/15","/ip4/198.51.100.0/ipcidr/24","/ip4/203.0.113.0/ipcidr/24","/ip4/240.0.0.0/ipcidr/4","/ip6/100::/ipcidr/64","/ip6/2001:2::/ipcidr/48","/ip6/2001:db8::/ipcidr/32","/ip6/fc00::/ipcidr/7","/ip6/fe80::/ipcidr/10"]'
  swarmAddrFilters: |
    '["/ip4/100.64.0.0/ipcidr/10","/ip4/169.254.0.0/ipcidr/16","/ip4/192.0.0.0/ipcidr/24","/ip4/192.0.2.0/ipcidr/24","/ip4/192.168.0.0/ipcidr/16","/ip4/198.18.0.0/ipcidr/15","/ip4/198.51.100.0/ipcidr/24","/ip4/203.0.113.0/ipcidr/24","/ip4/240.0.0.0/ipcidr/4","/ip6/100::/ipcidr/64","/ip6/2001:2::/ipcidr/48","/ip6/2001:db8::/ipcidr/32","/ip6/fc00::/ipcidr/7","/ip6/fe80::/ipcidr/10"]'

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

## Service
## ref: https://kubernetes.io/docs/concepts/services-networking/service/
##
service:
  type: ClusterIP
  containerPorts:
    gateway: 8082
  ports:
    p2p: 4001
    api: 5001
    gateway: 8080
    websocket: 8081

## Ingress
## ref: https://kubernetes.io/docs/concepts/services-networking/ingress/
##
ingress:
  api:
    enabled: false
    className: ""
    annotations: {}
      # kubernetes.io/ingress.class: nginx
      # kubernetes.io/tls-acme: "true"
    hosts:
      - host: chart-example.local
        paths:
          - path: /
            pathType: ImplementationSpecific
    tls: []
    #  - secretName: chart-example-tls
    #    hosts:
    #      - chart-example.local
  gateway:
    enabled: false
    className: ""
    annotations: {}
      # kubernetes.io/ingress.class: nginx
      # kubernetes.io/tls-acme: "true"
    hosts:
      - host: chart-example.local
        paths:
          - path: /
            pathType: ImplementationSpecific
    tls: []
    #  - secretName: chart-example-tls
    #    hosts:
    #      - chart-example.local

## Vertical Pod Autoscaler config
## Ref: https://github.com/kubernetes/autoscaler/tree/master/vertical-pod-autoscaler
##
verticalAutoscaler:
  ## If true a VPA object will be created for the StatefulSet
  enabled: false
  updateMode: Off
  containerPolicies: { }

## Configure resource requests and limits.
## http://kubernetes.io/docs/user-guide/compute-resources/
##
resources: { }

## If false, data ownership will not be reset at startup
## This allows the geth node to be run with an arbitrary user
##
initChownData: true

## Whether or not to allocate persistent volume disk for the data directory.
## In case of node failure, the node data directory will still persist.
##
persistence:
  enabled: true
  storageClassName: ""
  accessModes:
    - ReadWriteOnce
  dataSize: 25Gi
  fuseIpfsSize: 1Gi
  fuseIpnsSize: 1Gi

## Node labels for pod assignment
## ref: https://kubernetes.io/docs/user-guide/node-selection/
##
nodeSelector: {}

# hostNetwork
hostNetwork: false

## Tolerations for pod assignment
## ref: https://kubernetes.io/docs/concepts/configuration/taint-and-toleration/
##
tolerations: []

## Affinity for pod assignment
## ref: https://kubernetes.io/docs/concepts/configuration/assign-pod-node/#affinity-and-anti-affinity
##
affinity: {}

## used to assign priority to pods
## ref: https://kubernetes.io/docs/concepts/configuration/pod-priority-preemption/
##
priorityClassName: ""
