apiVersion: v1
kind: Secret
metadata:
  name: {{ include "common.names.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "common.labels.standard" . | nindent 4 }}
type: Opaque
data:
  OPERATOR_PRIVATE_KEY: {{ .Values.settings.oraclePrivateKey | b64enc | quote }}

{{- if .Values.settings.keystoresPassword }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "common.names.fullname" . }}-keystores-password
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "common.labels.standard" . | nindent 4 }}
type: Opaque
data:
  password.txt: {{ .Values.settings.keystoresPassword | b64enc | quote }}
{{- end }}
