{{- if not .Values.settings.executionEndpoint }}
{{- fail ".Values.settings.executionEndpoint is empty" }}
{{- end }}

{{- if not .Values.settings.consensusEndpoint }}
{{- fail ".Values.settings.consensusEndpoint is empty" }}
{{- end }}

{{- if not .Values.settings.hotWalletPrivateKey }}
{{- fail ".Values.settings.hotWalletPrivateKey is empty" }}
{{- end }}

{{- if not .Values.settings.vaultContractAddress }}
{{- fail ".Values.settings.vaultContractAddress is empty" }}
{{- end }}
