---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "common.names.fullname" . }}
  labels:
    {{- include "common.labels.standard" . | nindent 4 }}
{{- if and .Values.prysm.metrics.enabled .Values.prysm.metrics.svcAnnotations }}
  annotations:
    {{ toYaml .Values.prysm.metrics.svcAnnotations | nindent 4 | trim }}
{{- end }}
spec:
{{- if .Values.global.sessionAffinity.enabled }}
  sessionAffinity: ClientIP
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: {{ .Values.global.sessionAffinity.timeoutSeconds }}
{{- end }}
  type: ClusterIP
{{- if .Values.global.service.svcHeadless }}
  clusterIP: None
{{- end }}
  ports:
  {{- if .Values.nethermind.jsonrpc.enabled }}
    - port: {{ .Values.nethermind.jsonrpc.ports.rest }}
      targetPort: json-rest-neth
      protocol: TCP
      name: json-rest-neth
    - port: {{ .Values.nethermind.jsonrpc.ports.websocket }}
      targetPort: json-ws-neth
      protocol: TCP
      name: json-ws-neth
  {{- end }}
  {{- if or .Values.global.JWTSecret .Values.global.externalSecrets.enabled }}
    - port: {{ .Values.nethermind.jsonrpc.engine.port }}
      targetPort: engine-neth
      protocol: TCP
      name: engine-neth
  {{- end }}
  {{- if .Values.global.metrics.enabled }}
    - port: {{ .Values.nethermind.metrics.port }}
      targetPort: metrics-neth
      protocol: TCP
      name: metrics-neth
  {{- end }}
  {{- if .Values.prysm.http.enabled }}
    - name: http-beacon
      port: {{ .Values.prysm.http.port }}
      targetPort: http-beacon
  {{- end }}
  {{- if .Values.lighthouse.enabled }}
    - name: {{ .Values.lighthouse.http.portName }}
      port: {{ .Values.lighthouse.http.port }}
      targetPort: {{ .Values.lighthouse.http.portName }}
  {{- end }}
  {{- if .Values.teku.restApi.enabled }}
    - name: {{ .Values.teku.restApi.portName }}
      port: {{ .Values.teku.restApi.port }}
      targetPort: {{ .Values.teku.restApi.portName }}
      protocol: TCP
  {{- end }}
  {{- if .Values.global.metrics.enabled }}
    - name: metrics-beacon
      {{- if .Values.prysm.enabled }}
      port: {{ .Values.prysm.metrics.port }}
      {{- end }}
      {{- if .Values.lighthouse.enabled }}
      port: {{ .Values.lighthouse.metrics.port }}
      {{- end }}
      {{- if .Values.teku.enabled }}
      port: {{ .Values.teku.metrics.port }}
      {{- end }}
      targetPort: metrics-beacon
  {{- end }}
  selector:
    {{- include "common.labels.matchLabels" . | nindent 4 }}

