{{- $root := . -}}
{{- range $i, $e := until (int $root.Values.global.replicaCount) }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "common.names.fullname" $root }}-{{ $i }}
  labels:
    {{- include "common.labels.standard" $root | nindent 4 }}
    replicaID: {{ $i | quote }}
spec:
  type: {{ $root.Values.service.type }}
{{- if $root.Values.svcHeadless }}
  clusterIP: None
{{- end }}
{{- if $root.Values.sessionAffinity.enabled }}
  sessionAffinity: ClientIP
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: {{ $root.Values.sessionAffinity.timeoutSeconds }}
{{- end }}
  ports:
  {{- if $root.Values.jsonrpc.enabled }}
    - port: {{ $root.Values.jsonrpc.ports.rest }}
      targetPort: json-rest
      protocol: TCP
      name: json-rest
    - port: {{ $root.Values.jsonrpc.ports.websocket }}
      targetPort: json-ws
      protocol: TCP
      name: json-ws
  {{- end }}
  {{- if $root.Values.global.metrics.enabled }}
    - port: {{ $root.Values.metrics.port }}
      targetPort: metrics
      protocol: TCP
      name: metrics
  {{- end }}
  selector:
    {{- include "common.labels.matchLabels" $root | nindent 4 }}
    replicaID: {{ $i | quote }}

{{- end }}
