{{- if and .Values.enabled .Values.verticalAutoscaler.enabled }}
apiVersion: autoscaling.k8s.io/v1beta2
kind: VerticalPodAutoscaler
metadata:
  name: {{ include "common.names.fullname" . }}
  labels:
    {{- include "common.labels.standard" . | nindent 4 }}
spec:
  targetRef:
    apiVersion: "apps/v1"
    kind: StatefulSet
    name: {{ include "common.names.fullname" . }}
  updatePolicy:
    updateMode: {{ .Values.verticalAutoscaler.updateMode | default "Off" | quote }}
  {{- if .Values.verticalAutoscaler.containerPolicies }}
  resourcePolicy:
    containerPolicies:
      {{ tpl .Values.verticalAutoscaler.containerPolicies . | nindent 6 | trim }}
  {{- end }}
{{- end }}
