apiVersion: v2
name: nethermind
description: .NET Core Ethereum client
type: application
version: 2.8.2
appVersion: "v1.31.8"
icon: https://storage.googleapis.com/stakewise-charts/stakewise.png
keywords:
  - ethereum
  - blockchain
  - nethermind
  - p2p
home: https://nethermind.io/
sources:
  - https://github.com/NethermindEth/nethermind

dependencies:
  - name: common
    repository: https://charts.stakewise.io/
    version: 1.x.x
