apiVersion: v2
name: keeper
version: 2.8.12
appVersion: v2.8.10
kubeVersion: "^1.14.0-0"
description: StakeWise Keeper is used to aggregate transactions from the oracles and submit them on-chain.
type: application
keywords:
  - ethereum
  - blockchain
  - staking
home: https://stakewise.io/
sources:
  - https://github.com/stakewise/keeper/
maintainers:
  - name: Dmitri Tsumak
    email: dmitri@stakewise.io

dependencies:
- name: common
  repository: https://charts.stakewise.io/
  version: 1.x.x
