apiVersion: v2
name: geth
version: 2.1.4
kubeVersion: "^1.18.0-0"
description: Official Golang implementation of the Ethereum v1 protocol.
type: application
keywords:
  - ethereum
  - blockchain
  - geth
  - p2p
home: https://www.ethereum.org/
sources:
  - https://github.com/ethereum/go-ethereum/
maintainers:
  - name: Dmitri Tsumak
    email: dmitri@stakewise.io
icon: https://raw.githubusercontent.com/ethereum/ethereum-org/master/public/images/logos/ETHEREUM-ICON_Black.png
appVersion: v1.10.24

dependencies:
  - name: common
    version: 1.x.x
    repository: "file://../common"
