apiVersion: v2
name: geth
version: 2.5.3
kubeVersion: "^1.20.0-0"
description: Official Golang implementation of the Ethereum v1 protocol.
type: application
icon: https://storage.googleapis.com/stakewise-charts/stakewise.png
keywords:
  - ethereum
  - blockchain
  - geth
  - p2p
home: https://www.ethereum.org/
sources:
  - https://github.com/ethereum/go-ethereum/
maintainers:
  - name: Dmitri Tsumak
    email: dmitri@stakewise.io
appVersion: v1.15.2

dependencies:
  - name: common
    version: 1.x.x
    repository: https://charts.stakewise.io/
