apiVersion: v2
name: v3-backend
version: 3.1.6
appVersion: v0.3.6
kubeVersion: "^1.20.0-0"
description: The StakeWise backend application.
type: application
keywords:
  - ethereum
  - blockchain
  - staking
home: https://stakewise.io/
sources:
  - https://github.com/stakewise/v3-backend/
dependencies:
  - name: common
    version: 1.x.x
    repository: https://charts.stakewise.io/
  - name: postgresql
    version: 12.1.6
    repository: https://charts.bitnami.com/bitnami/
    condition: postgresql.enabled
  - name: rabbitmq
    version: 11.3.0
    repository: https://charts.bitnami.com/bitnami/
    condition: rabbitmq.enabled
  - name: memcached
    version: 6.3.2
    repository: https://charts.bitnami.com/bitnami/
    condition: memcached.enabled
  - name: ipfs
    version: 1.x.x
    repository: https://charts.stakewise.io/
    condition: ipfs.enabled
maintainers:
  - name: Dmitri Tsumak
    email: dmitri@stakewise.io
