global:
  serviceAccount:
    create: true

## Application settings
##
settings:
  ## Possible values: goerli, perm_goerli, gnosis, mainnet, harbour_goerli, harbour_mainnet
  ##
  network: mainnet
  logLevel: "INFO"
  celeryConcurrency: "8"

  sendEmails: "False"
  ## Change to https://api.mailgun.net/v3
  ## if you are using Mailgunâ€™s US region
  ##
  mailgunApiUrl: "https://api.eu.mailgun.net/v3"
  mailgunApiKey: ""
  mailgunSenderDomain: "mail.stakewise.io"
  defaultFromEmail: '"Stakewise" <no-reply@mail.stakewise.io>'

  sentryDsn: ""

  sendTelegramNotifaction: "false"

  beaconchaApiToken: ""

  telegramToken: ""
  telegramChatId: ""
  multisigOwnersTelegramToken: ""
  multisigOwnersTelegramChatId: ""

  gcpStorageContentBucket: ""
  gcpStorageOauthCredentials: ""
  gcpStorageDomainAlias: ""
  gcpStorageIpfsBucket: ""
  gcpPerspectiveApiKey: ""
  gcpCloudVisionApiKey: ""

  ipfsLocalClientEndpoint: ""
  ipfsPinataPinEndpoints: "https://api.pinata.cloud/pinning/pinJSONToIPFS"
  ipfsFetchEndpoints: '["http://cloudflare-ipfs.com","https://ipfs.io","https://gateway.pinata.cloud"]'
  ipfsInfuraClientUsername: ""
  ipfsInfuraClientPassword: ""
  ipfsPinataApiKey: ""
  ipfsPinataSecretKey: ""
  ipfsFilebaseBucket: ""
  ipfsFilebaseAPIToken: ""
  ipfsQuikcnodeAPIToken: ""

  executionEndpoints: ""
  consensusEndpoints: ""
  mainnetExecutionEndpoints: ""
  mainnetConsensusEndpoints: ""
  gnosisExecutionEndpoints: ""
  gnosisConsensusEndpoints: ""
  consensusTimeout: "30"
  consensusRetryTimeout: "60"

  memcachedUrl: ""
  brokerUrl: ""

  ratedApiBearerToken: ""

  graph:
    APIUrl: ""
    postgresHost: ""
    postgresPort: ""
    postgresDB: ""
    postgresUser: ""
    postgresPassword: ""
    vaultsTable: ""
    exitRequestsTable: ""
  fallbackGraph:
    postgresHost: ""
    postgresPort: ""
    postgresDB: ""
    postgresUser: ""
    postgresPassword: ""
    vaultsTable: ""
    exitRequestsTable: ""
  stageGraph:
    postgresHost: ""
    postgresPort: ""
    postgresDB: ""
    postgresUser: ""
    postgresPassword: ""
    vaultsTable: ""
    exitRequestsTable: ""

  postgres:
    host: localhost
    port: "5432"
    db: v3-backend
    user: ""
    password: ""

image:
  registry: "europe-west4-docker.pkg.dev"
  repository: "stakewiselabs/private/v3-backend"
  tag: "v2.0.27"
  pullPolicy: IfNotPresent
  pullSecrets: []

serviceAccount:
  ## Annotations to add to the service account
  ##
  annotations: {}

app:
  ## How many api pods to run simultaneously.
  ##
  replicaCount: 2

  ## Enable pod disruption budget.
  ## ref: https://kubernetes.io/docs/concepts/workloads/pods/disruptions/
  ##
  podDisruptionBudget:
    enabled: true
    maxUnavailable: 1

  ## "Host" Header value to pass with the request for Host verification.
  ##
  probesHostHeader: "api-v3.stakewise.io"

  serviceType: ClusterIP
  servicePort: "8000"

  ## Configure ingress
  ## ref: https://kubernetes.io/docs/concepts/services-networking/ingress/
  ##
  ingress:
    enabled: true
    className: ""
    annotations: {}
    tls: []
    path: "/"
    hosts: []

  ## Configure resource requests and limits.
  ## ref: http://kubernetes.io/docs/user-guide/compute-resources/
  ##
  resources:
    requests:
      cpu: 100m
      memory: 512Mi
    limits:
      cpu: 1000m
      memory: 1024Mi

  ## Pod Security Context
  ## ref: https://kubernetes.io/docs/tasks/configure-pod-container/security-context/
  ##
  securityContext:
    fsGroup: 65534
    runAsUser: 65534

  ## Tolerations for pod assignment
  ## ref: https://kubernetes.io/docs/concepts/configuration/taint-and-toleration/
  ##
  tolerations: []

  ## Affinity for pod assignment
  ## ref: https://kubernetes.io/docs/concepts/configuration/assign-pod-node/#affinity-and-anti-affinity
  ##
  affinity: {}

  ## used to assign priority to pods
  ## ref: https://kubernetes.io/docs/concepts/configuration/pod-priority-preemption/
  ##
  priorityClassName: ""

admin:
  ## How many api pods to run simultaneously.
  ##
  replicaCount: 1

  ## Enable pod disruption budget.
  ## ref: https://kubernetes.io/docs/concepts/workloads/pods/disruptions/
  ##
  podDisruptionBudget:
    enabled: true
    maxUnavailable: 1

  ## "Host" Header value to pass with the request for Host verification.
  ##
  probesHostHeader: "admin-v3.stakewise.io"

  serviceType: ClusterIP
  servicePort: "8000"

  ## Configure ingress
  ## ref: https://kubernetes.io/docs/concepts/services-networking/ingress/
  ##
  ingress:
    enabled: true
    className: ""
    annotations: {}
    tls: []
    path: "/"
    hosts: []

  ## Configure resource requests and limits.
  ## ref: http://kubernetes.io/docs/user-guide/compute-resources/
  ##
  resources:
    requests:
      cpu: 100m
      memory: 512Mi
    limits:
      cpu: 1000m
      memory: 1024Mi

  ## Pod Security Context
  ## ref: https://kubernetes.io/docs/tasks/configure-pod-container/security-context/
  ##
  securityContext:
    fsGroup: 65534
    runAsUser: 65534

  ## Tolerations for pod assignment
  ## ref: https://kubernetes.io/docs/concepts/configuration/taint-and-toleration/
  ##
  tolerations: []

  ## Affinity for pod assignment
  ## ref: https://kubernetes.io/docs/concepts/configuration/assign-pod-node/#affinity-and-anti-affinity
  ##
  affinity: {}

  ## used to assign priority to pods
  ## ref: https://kubernetes.io/docs/concepts/configuration/pod-priority-preemption/
  ##
  priorityClassName: ""

worker:
  priorityClassName: ""

  ## Pod Security Context
  ## ref: https://kubernetes.io/docs/tasks/configure-pod-container/security-context/
  ##
  securityContext:
    fsGroup: 65534
    runAsUser: 65534

  ## Tolerations for pod assignment
  ## ref: https://kubernetes.io/docs/concepts/configuration/taint-and-toleration/
  ##
  tolerations: []

  ## Affinity for pod assignment
  ## ref: https://kubernetes.io/docs/concepts/configuration/assign-pod-node/#affinity-and-anti-affinity
  ##
  affinity: {}

  ## How many celery worker pods to run simultaneously.
  ##
  replicaCount: 2

  ## Configure resource requests and limits.
  ## ref: http://kubernetes.io/docs/user-guide/compute-resources/
  ##
  resources:
    requests:
      cpu: 1000m
      memory: 512Mi
    limits:
      cpu: 1000m
      memory: 1024Mi

beat:
  priorityClassName: ""

  ## Pod Security Context
  ## ref: https://kubernetes.io/docs/tasks/configure-pod-container/security-context/
  ##
  securityContext:
    fsGroup: 65534
    runAsUser: 65534

  ## Tolerations for pod assignment
  ## ref: https://kubernetes.io/docs/concepts/configuration/taint-and-toleration/
  ##
  tolerations: []

  ## Affinity for pod assignment
  ## ref: https://kubernetes.io/docs/concepts/configuration/assign-pod-node/#affinity-and-anti-affinity
  ##
  affinity: {}

  ## How many celery worker pods to run simultaneously.
  ##
  replicaCount: 1

  ## Configure resource requests and limits.
  ## ref: http://kubernetes.io/docs/user-guide/compute-resources/
  ##
  resources:
    requests:
      cpu: 1000m
      memory: 512Mi
    limits:
      cpu: 1000m
      memory: 1024Mi

## Prometheus Service Monitor
## ref: https://github.com/coreos/prometheus-operator
##      https://github.com/coreos/prometheus-operator/blob/master/Documentation/api.md#endpoint
##
serviceMonitor:
  enabled: false
  ## The namespace in which the ServiceMonitor will be created
  ##
  namespace: ""
  ## The interval at which metrics should be scraped
  ##
  interval: 30s
  ## The timeout after which the scrape is ended
  ##
  scrapeTimeout: ""
  ## Metrics RelabelConfigs to apply to samples before scraping.
  ##
  relabellings: []
  ## Metrics RelabelConfigs to apply to samples before ingestion.
  ##
  metricRelabelings: []
  ## Specify honorLabels parameter to add the scrape endpoint
  ##
  honorLabels: false
  ## Additional labels that can be used so ServiceMonitor resource(s) can be discovered by Prometheus
  ##
  additionalLabels: {}

cloudsqlProxy:
  enabled: false
  replicaCount: 1
  instance: ""
  serviceAccountKey: ""

postgresql:
  enabled: false

rabbitmq:
  enabled: true
  auth:
    username: "rabbitmq"
    password: "rabbitmq"
  persistence:
    enabled: false

memcached:
  enabled: true
  architecture: standalone
  auth:
    enabled: false

## IPFS Server
##
ipfs:
  enabled: true
