apiVersion: v2
description: 'Nethermind is an Ethereum execution layer implementation created with
  the C# .NET tech stack, running on all major platforms including ARM. '
home: https://nethermind.io/
icon: https://launchpad.ethereum.org/static/media/nethermind-circle.fbbf1a32.png
maintainers:
- email: rafael@skyle.net
  name: skylenet
- email: busa.barnabas@gmail.com
  name: barnabasbusa
name: nethermind
sources:
- https://github.com/NethermindEth/nethermind
type: application
version: 1.0.9
