apiVersion: v2
name: v3-oracle
version: 3.2.2
appVersion: v0.5.1
kubeVersion: "^1.14.0-0"
description: The StakeWise application for submitting off-chain data to smart contracts.
type: application
keywords:
  - ethereum
  - blockchain
  - staking
home: https://stakewise.io/
sources:
  - https://github.com/stakewise/oracle/
maintainers:
  - name: Dmitri Tsumak
    email: dmitri@stakewise.io

dependencies:
- name: common
  repository: https://charts.stakewise.io/
  version: 1.x.x
- name: ipfs
  repository: https://charts.stakewise.io/
  version: 2.x.x
  condition: ipfs.enabled
