apiVersion: v2
name: nimbus
version: 2.3.1
kubeVersion: "^1.18.0-0"
description: Nim implementation of the Ethereum Beacon Chain
type: application
icon: https://storage.googleapis.com/stakewise-charts/stakewise.png
keywords:
  - ethereum
  - blockchain
  - nimbus
  - p2p
home: https://www.ethereum.org/
sources:
  - https://github.com/status-im/nimbus-eth2
maintainers:
  - name: Dmitri Tsumak
    email: dmitri@stakewise.io
appVersion: multiarch-v25.3.1

dependencies:
  - name: common
    repository: https://charts.stakewise.io/
    version: 1.x.x
