{{- $root := . -}}
{{- range $i, $e := until (len $root.Values.global.executionEndpoints) }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "common.names.fullname" $root }}-{{ $i }}
  labels:
    {{- include "common.labels.standard" $root | nindent 4 }}
    repliaID: {{ $i | quote }}
{{- if and $root.Values.metrics.enabled $root.Values.metrics.svcAnnotations }}
  annotations:
    {{ toYaml $root.Values.metrics.svcAnnotations | nindent 4 | trim }}
{{- end }}
spec:
  selector:
    {{- include "common.labels.matchLabels" $root | nindent 4 }}
    repliaID: {{ $i | quote }}
{{- if $root.Values.sessionAffinity.enabled }}
  sessionAffinity: ClientIP
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: {{ $root.Values.sessionAffinity.timeoutSeconds }}
{{- end }}
  type: ClusterIP
{{- if $root.Values.svcHeadless }}
  clusterIP: None
{{- end }}
  ports:
    - name: {{ $root.Values.http.portName }}
      port: {{ $root.Values.http.port }}
      targetPort: {{ $root.Values.http.portName }}
  {{- if $root.Values.metrics.enabled }}
    - name: metrics
      port: {{ $root.Values.metrics.port }}
      targetPort: metrics
  {{- end }}

{{- end }}
