apiVersion: v2
name: backend
version: 2.4.24
appVersion: v2.4.23
kubeVersion: "^1.18.0-0"
description: The StakeWise backend application.
type: application
keywords:
  - ethereum
  - blockchain
  - staking
home: https://stakewise.io/
sources:
  - https://github.com/tsudmi/backend/
dependencies:
  - name: common
    version: 1.x.x
    repository: https://charts.stakewise.io/
  - name: postgresql
    version: 12.1.7
    repository: https://charts.bitnami.com/bitnami/
    condition: postgresql.enabled
  - name: rabbitmq
    version: 11.3.1
    repository: https://charts.bitnami.com/bitnami/
    condition: rabbitmq.enabled
  - name: memcached
    version: 6.3.3
    repository: https://charts.bitnami.com/bitnami/
    condition: memcached.enabled
maintainers:
  - name: Dmitri Tsumak
    email: dmitri@stakewise.io
