apiVersion: v2
name: backend
version: 2.2.0
appVersion: v2.2.0
kubeVersion: "^1.18.0-0"
description: The StakeWise backend application.
type: application
keywords:
  - ethereum
  - blockchain
  - staking
home: https://stakewise.io/
sources:
  - https://github.com/tsudmi/backend/
dependencies:
  - name: postgresql
    version: 10.13.8
    repository: https://charts.bitnami.com/bitnami/
    condition: postgresql.enabled
maintainers:
  - name: Dmitri Tsumak
    email: dmitri@stakewise.io
