apiVersion: v2
name: geth-prysm
version: 0.1.0
appVersion: 0.1.0
kubeVersion: "^1.18.0-0"
description: Geth and Prysm
type: application
keywords:
  - ethereum
  - blockchain
  - geth
  - prysm
  - p2p
home: https://www.ethereum.org/
sources:
  - https://github.com/ethereum/go-ethereum/
  - https://github.com/prysmaticlabs/prysm
maintainers:
  - name: Dmitri Tsumak
    email: dmitri@stakewise.io
icon: https://raw.githubusercontent.com/ethereum/ethereum-org/master/public/images/logos/ETHEREUM-ICON_Black.png

dependencies:
  - name: common
    repository: file://../common
    version: 1.0.0
